### ISSUE TITLE
Crash when inflating view on Android

### ISSUE THREAD

**Issue by petr-pokorny-1** [maplibre/maplibre-gl-native#117]
While using the android-sdk:9.5.0, the following code in the MainActivity

```kotlin
override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)

    Mapbox.getInstance(this)
      // Inflate the view
    setContentView(R.layout.activity_main)
  ...
}
```

This should initialize the SDK using default MapLibre configuration while not requiring API key. It causes the following crash:

```
A/iler.helloworl: runtime.cc:630]   at android.os.Looper.loop(Looper.java:214)
    runtime.cc:630]   at android.app.ActivityThread.main(ActivityThread.java:7356)
    runtime.cc:630]   at java.lang.reflect.Method.invoke(Native method)
    runtime.cc:630]   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
    runtime.cc:630]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
    runtime.cc:630] 
    runtime.cc:638] JNI DETECTED ERROR IN APPLICATION: field operation on NULL object: 0x0
    runtime.cc:638]     in call to GetObjectField
    runtime.cc:638]     from void com.mapbox.mapboxsdk.storage.FileSource.initialize(java.lang.String, java.lang.String, com.mapbox.mapboxsdk.util.TileServerOptions)
    runtime.cc:638] 
A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 15304 (iler.helloworld), pid 15304 (iler.helloworld)
```

The overload does not cause the crash

```
Mapbox.getInstance(this, "key", WellKnownTileServer.XXX)
```

**Comment by miallo** [comment]
We ran into the same issue and building it is a bit involved. The main branch seems to work with #130 included. We noticed that `platform/android/MapboxGLAndroidSDK/gradle.properties` still has the version `9.1.0` in it and it should this be in sync with the release.

Could you just create an android pre-release with the fix for this issue? Hopefully this is not too difficult :)

**Comment by petr-pokorny-1** [comment]
https://github.com/maplibre/maplibre-gl-native/pull/130
