### ISSUE TITLE
Android test app fails in native methods: no "D" field "latitudeSouth" in class "LatLngBounds;" or its superclasses

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-gl-native#648]
**Describe the bug**
When I run the LatLngBounds Method, the app crashes with the following stack trace:

```
2023-01-04 13:29:02.438 23535-23535/com.mapbox.mapboxsdk.testapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mapbox.mapboxsdk.testapp, PID: 23535
    java.lang.NoSuchFieldError: no "D" field "latitudeSouth" in class "Lcom/mapbox/mapboxsdk/geometry/LatLngBounds;" or its superclasses
        at com.mapbox.mapboxsdk.maps.NativeMapView.nativeGetCameraForLatLngBounds(Native Method)
        at com.mapbox.mapboxsdk.maps.NativeMapView.getCameraForLatLngBounds(NativeMapView.java:280)
        at com.mapbox.mapboxsdk.maps.MapboxMap.getCameraForLatLngBounds(MapboxMap.java:1569)
        at com.mapbox.mapboxsdk.maps.MapboxMap.getCameraForLatLngBounds(MapboxMap.java:1531)
        at com.mapbox.mapboxsdk.testapp.activity.camera.LatLngBoundsActivity.initMapView$lambda$1(LatLngBoundsActivity.kt:55)
        at com.mapbox.mapboxsdk.testapp.activity.camera.LatLngBoundsActivity.$r8$lambda$hMTeKg1QgKBl1JjTOscJBn3PmlA(Unknown Source:0)
        at com.mapbox.mapboxsdk.testapp.activity.camera.LatLngBoundsActivity$$ExternalSyntheticLambda2.onMapReady(Unknown Source:2)
        at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onMapReady(MapView.java:1322)
        at com.mapbox.mapboxsdk.maps.MapView$MapCallback.initialised(MapView.java:1308)
        at com.mapbox.mapboxsdk.maps.MapView.initialiseMap(MapView.java:203)
        at com.mapbox.mapboxsdk.maps.MapView.access$800(MapView.java:65)
        at com.mapbox.mapboxsdk.maps.MapView$6.run(MapView.java:355)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7664)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
2023-01-04 13:29:02.471 23535-23535/com.mapbox.mapboxsdk.testapp I/Process: Sending signal. PID: 23535 SIG: 9
```

**To Reproduce**
1. Run the MapboxGLAndroidSDKTestApp
2. Open the "LatLngBounds Method" activity

**Expected behavior**
Activity is shown.

**Platform information (please complete the following information):**
 - Platform Android
 - Version `main` branch

**Comment by louwers** [comment]
The same issue is crashing the DownloadRegionActivity upon download start:

```
2023-01-04 15:00:09.000 31800-31800/com.mapbox.mapboxsdk.testapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mapbox.mapboxsdk.testapp, PID: 31800
    java.lang.NoSuchFieldError: no "D" field "latitudeSouth" in class "Lcom/mapbox/mapboxsdk/geometry/LatLngBounds;" or its superclasses
        at com.mapbox.mapboxsdk.offline.OfflineManager.createOfflineRegion(Native Method)
        at com.mapbox.mapboxsdk.offline.OfflineManager.createOfflineRegion(OfflineManager.java:618)
        at com.mapbox.mapboxsdk.testapp.activity.offline.DownloadRegionActivity.createOfflineRegion(DownloadRegionActivity.kt:88)
        at com.mapbox.mapboxsdk.testapp.activity.offline.DownloadRegionActivity.initFab$lambda$4(DownloadRegionActivity.kt:274)
        at com.mapbox.mapboxsdk.testapp.activity.offline.DownloadRegionActivity.$r8$lambda$3u7ashrd3pB5eKy3VmogXTk3UJw(Unknown Source:0)
        at com.mapbox.mapboxsdk.testapp.activity.offline.DownloadRegionActivity$$ExternalSyntheticLambda0.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:7448)
        at android.view.View.performClickInternal(View.java:7425)
        at android.view.View.access$3600(View.java:810)
        at android.view.View$PerformClick.run(View.java:28305)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7664)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by artakka** [comment]
Looking
