### ISSUE TITLE
node-pre-gyp: binding.gyp not found

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-gl-native#851]
When running `npm install` from the root directory, I am getting this error: 

<details>
  <summary>node-pre-gyp: binding.gyp not found</summary>

```
npm WARN deprecated async-cache@1.1.0: No longer maintained. Use [lru-cache](http://npm.im/lru-cache) version 7.6 or higher, and provide an asynchronous `fetchMethod` option.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated mapbox-gl-styles@2.0.2: This package has moved to the @mapbox namespace. All new version are available via @mapbox/mapbox-gl-styles

> @maplibre/maplibre-gl-native@5.1.1 install
> node-pre-gyp install --fallback-to-build=true

node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.11
node-pre-gyp info using node@19.6.0 | linux | x64
node-pre-gyp info check checked for "/home/bart/src/maplibre-gl-native/lib/node-v111/mbgl.node" (not found)
node-pre-gyp http GET https://github.com/maplibre/maplibre-gl-native/releases/download/node-v5.1.1/node-v111-linux-x64-Release.tar.gz
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/maplibre/maplibre-gl-native/releases/download/node-v5.1.1/node-v111-linux-x64-Release.tar.gz 
node-pre-gyp WARN Pre-built binaries not installable for @maplibre/maplibre-gl-native@5.1.1 and node@19.6.0 (node-v111 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/maplibre/maplibre-gl-native/releases/download/node-v5.1.1/node-v111-linux-x64-Release.tar.gz 
gyp info it worked if it ends with ok
gyp info using node-gyp@9.3.1
gyp info using node@19.6.0 | linux | x64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@9.3.1
gyp info using node@19.6.0 | linux | x64
gyp info find Python using Python version 3.10.9 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/usr/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/bart/src/maplibre-gl-native/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/bart/.cache/node-gyp/19.6.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/bart/.cache/node-gyp/19.6.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/bart/.cache/node-gyp/19.6.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/bart/src/maplibre-gl-native',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp: binding.gyp not found (cwd: /home/bart/src/maplibre-gl-native) while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/node-gyp/lib/configure.js:325:16)
gyp ERR! stack     at ChildProcess.emit (node:events:512:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:293:12)
gyp ERR! System Linux 6.1.9-arch1-2
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build=true" "--module=/home/bart/src/maplibre-gl-native/lib/node-v111/mbgl.node" "--module_name=mbgl" "--module_path=/home/bart/src/maplibre-gl-native/lib/node-v111" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v111"
gyp ERR! cwd /home/bart/src/maplibre-gl-native
gyp ERR! node -v v19.6.0
gyp ERR! node-gyp -v v9.3.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build=true --module=/home/bart/src/maplibre-gl-native/lib/node-v111/mbgl.node --module_name=mbgl --module_path=/home/bart/src/maplibre-gl-native/lib/node-v111 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v111' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/bart/src/maplibre-gl-native/node_modules/@acalcutt/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:512:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1098:16)
node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:304:5)
node-pre-gyp ERR! System Linux 6.1.9-arch1-2
node-pre-gyp ERR! command "/usr/bin/node" "/home/bart/src/maplibre-gl-native/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build=true"
node-pre-gyp ERR! cwd /home/bart/src/maplibre-gl-native
node-pre-gyp ERR! node -v v19.6.0
node-pre-gyp ERR! node-pre-gyp -v v1.0.11
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build=true --module=/home/bart/src/maplibre-gl-native/lib/node-v111/mbgl.node --module_name=mbgl --module_path=/home/bart/src/maplibre-gl-native/lib/node-v111 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v111' (1)
npm ERR! code 1
npm ERR! path /home/bart/src/maplibre-gl-native
npm ERR! command failed
npm ERR! command sh -c -- node-pre-gyp install --fallback-to-build=true

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bart/.npm/_logs/2023-02-23T10_12_14_837Z-debug-0.log
```
</details>

Any ideas? I am using Node v19.6.0. I get the same error on macOS.

Should we even run `node-pre-gyp` on install? Because the package.json in the root specifies the dependencies for the scripts as well, which do not need it.

**Comment by acalcutt** [comment]
we don't have node binaries for node 19. if you want to build on a unsupported system, you need to star with

**Comment by louwers** [comment]
@acalcutt Thanks!

**Comment by acalcutt** [comment]
Basically on install, the node-pre-gyp plugin tries to download a pre-compiled binary from the [spot specified in package.json](https://github.com/maplibre/maplibre-gl-native/blob/main/package.json#L71-L72), like
https://github.com/maplibre/maplibre-gl-native/releases/tag/node-v5.1.1

If there are no binaries for your system, there is no fallback right now. It used to build on its own if node-pre-gyp failed, but that was removed in https://github.com/mapbox/mapbox-gl-native/pull/15748 . My cmake-js PR would bring back the ability for this build on it's on back https://github.com/maplibre/maplibre-gl-native/pull/535

**Comment by louwers** [comment]
@acalcutt Would it make sense to move the `package.json` for the Node.js bindings to `platform/node` and use the one in the root as dependencies for the scripts?

Or perhaps split those out into a `scripts/package.json`?

**Comment by acalcutt** [comment]
not really sure. it needs to be part of the npm package install, so when it is used as a package it pulls in the binaries. It was always part of the core package.

**Comment by acalcutt** [comment]
if it was moved I don't think it would matter as long as the package name stays the same.
